version: "3"

volumes:
  node_modules:

services:
  web:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "3000:3000"
      - "24678:24678"

    volumes:
      - .:/src
      - node_modules:/src/node_modules
